### ISSUE TITLE
Firmware install guide

### ISSUE THREAD

**Issue by moonglow** [moonglow/FlashForge_Marlin#1]
Make sure what you have installed:
- Python 3
- pyusb package
- libusb

`FILENAME` - firmware file what we need to upload to printer, change it according your needs

Flashing firmware:

- Turn on printer and while boot logo will start to draw you need try to start script
- If script failed with `Operation timed out` it is OK try to restart script 2-4 times ( printer boot process will be suspended )

Success script output
```
b'CMD M601 Received.\r\nControl Success.\r\nok\r\n'
b'CMD M28 Received.\r\n'
b'Writing to file: dreamerx.bin\r\nok\r\n'
b'CMD M29 Received.\r\n'
b'Done saving file.\r\nok\r\n'
b'CMD M600 Received.\r\n'
b'succeed\r\nok\r\n'
b'CMD M600 Received.\r\n'
b'succeed\r\nok\r\n'
```
After 10-20 seconds bootloader will start to update firmware and then reboot automatically.

Note:
First of all try to flash original firmware to your printer to make sure what you understand how it works !!!

**Comment by tckb** [comment]
Is itr possible to flash it via Flashprint? I ask this because I flashed the "heating fix"  via Flashprint

**Comment by moonglow** [comment]
Yep! Sure you can, but you must also understand that next update you need to do via bootloader :) because you be on Marlin.

**Comment by tckb** [comment]
Ah! is this is different step that'd be via the script?

**Comment by moonglow** [comment]
Yep, FlashPrint works with main software and copy firmware to internal uSD card ( and do some mark in flash ). Then you reboot your printer bootloader see that marks and write firmware from internal uSD card to flash.

Scrip allow you write firmware via bootloader so you no need to have original firmware. Whan bootloader start and init ther own USB connection it wait some time for commands, if no commands comes to bootloader it will start firmware.

**Comment by moonglow** [comment]
Windows FlashPrint driver already based on libusb and under Windows you need only install ( untested  ):

1. Install Python3 from [here](https://www.python.org/downloads/)
2. Install pyusb module: pyusb: `python -m pip install pyusb`

**Comment by tckb** [comment]
@moonglow  I've added some handy script improvements  #8
