### ISSUE TITLE
Control Failed error

### ISSUE THREAD

**Issue by TiopaSnow** [moonglow/FlashForge_Marlin#103]
![image](https://user-images.githubusercontent.com/49413302/163599735-5a1fc1ba-1a55-4f49-9ff9-4a2d0034c18b.png)
i keep getting a control failed error,

**Comment by moonglow** [comment]
Hi @TiopaSnow  !

Can you provide more info ( step-by-step ) ? 

p.s:  @Mrnt provides great update to firmware update script it works very stable, but only under Linux like systems

**Comment by TiopaSnow** [comment]
Downloaded and unzipped ff writer, downloaded and upzipped into the same folder the color ui, started ff writer, browsed to the nx printer files, hit start, turned on printer, printer gets past the boot loader and plays loud single note. says connected, then says connection failed

**Comment by TiopaSnow** [comment]
Printer is connected to computer through usb

**Comment by Mrnt** [comment]
What if you try hitting the reset button on the printer and immediately hit the Start button on the FF Firmware Writer?

**Comment by TiopaSnow** [comment]
same problem

**Comment by TiopaSnow** [comment]
printer firmware is 1.9 20191123

**Comment by TiopaSnow** [comment]
I dont have any older versions to change to either

**Comment by TiopaSnow** [comment]
Found the oldest firmware, 1.2 20190320, still the same problem

**Comment by Mrnt** [comment]
Please provide printer model.
Do you only have a Windows computer? No RaspberryPi, etc? Do you have Python installed on the Windows computer?

**Comment by TiopaSnow** [comment]
Dreamer NX, yes just a windows pc, no python

**Comment by TiopaSnow** [comment]
Do I need a raspberry pi and python? They were not listed in the instructions

**Comment by Mrnt** [comment]
No you should not need them. I was asking because the alternative firmware installation script (which is primarily intended for Linux, MacOS) is a Python script. Wanted to see if you had access to a means to use the alternative method.

@moonglow could this be a code signing issue?

**Comment by TiopaSnow** [comment]
I don't know if it matters but I'm in windows 7

**Comment by Mrnt** [comment]
You are not using FlashPrint when trying to use the firmware updater?

**Comment by TiopaSnow** [comment]
yes

**Comment by Mrnt** [comment]
OOPS I updated my comment above by accident:

You are not using FlashPrint when trying to use the firmware updater?

re FlashPrint: I'm asking because I think it may be possible to use FlashPrint to send the firmware to the printer. Also to verify that there is not a PC/printer communication issue.

**Comment by TiopaSnow** [comment]
I am not using flashprint per the instructions flashprint is closed

**Comment by TiopaSnow** [comment]
per*

**Comment by TiopaSnow** [comment]
I got flashprint to install it, i changed the 1.2 bin file name and renamed the marlin file to its name, fflashprint installed it for me

**Comment by Mrnt** [comment]
Great! That's what I was going to suggest, didn't know where FlashPrint looked on Windows for the bin files.
Maybe you could provide the file path FlashPrint for Windows uses?

**Comment by TiopaSnow** [comment]
C:/program files/flashforge/flashprint/firmware/

**Comment by TiopaSnow** [comment]
New problem when trying to print I get: m907 overcurrent please reboot

**Comment by TiopaSnow** [comment]
Do I need to tell cura it's a different printer now?

**Comment by Mrnt** [comment]
did you see this:
https://github.com/moonglow/FlashForge_Marlin/wiki/%5BATTENTION%5D-Avoid-using-FlashForge-original-firmware-G-Codes

**Comment by TiopaSnow** [comment]
i did now lol
