### ISSUE TITLE
Rear case fan

### ISSUE THREAD

**Issue by moonglow** [moonglow/FlashForge_Marlin#11]
From v0.6 rear case fan logic was fixed and now it works as expected

1. By default chamber cool-down temperature is 45℃
2. If you want to use chamber fan from G-Code you need to disable temperature logic by set cool-down temp to 0 or from Menu->Rear Case->Disable Rear Case Fan
3. You can increase cool-down temperature if you want from main menu or from Menu->Temperature->Enclosure
3. Chamber fan index is 2 ( Marlin hardcoded value ) , so you can access it via `M106 P2 S<speed>` ( make sure what you disable cool-down logic before )

**Comment by TiopaSnow** [comment]
So Dreamer NX case fan for my printer did not have an index of 2, it has an index of 1, so M106 P1 S100 puts my case fans at full

**Comment by fbb034** [comment]
I'm using dreamer_2.0.9.3_swap_04242022 but the case fan wont respond to any gcodes (M106 P2 S200). I have set the cooldown to  0 and also disabled it in the menu. What am I doing wrong?

**Comment by moonglow** [comment]
@fbb034 Hi !

Chamber fan index was hardcoded by old Marlin release and now ( from 2.0.9.3 it was configurable, so you can try to use M106 P1 command to control it ) , refer to our pinmap [PINMAP_LINK](https://github.com/moonglow/FlashForge_Marlin/blob/marlin_2.0.x/Marlin/Marlin/src/pins/stm32f4/pins_FF_MOTHERBOARD.h)

p.s: @TiopaSnow is also refer to that

**Comment by fbb034** [comment]
I tried M106 P1 but that only turns on the part cooling fan. Sorry but I don't know wat to do with your pinmap

**Comment by moonglow** [comment]
@fbb034 i will test it and report you back, you can try also with P2 but change chamber temp to something like 60 or etc.... to disable automatically run of FAN and try again to control it, i think it can make a sense for such FAN

**Comment by fbb034** [comment]
The rear case fan is still not functional after setting the fan temp to 50 (max).

**Comment by moonglow** [comment]
@fbb034 Sorry for long answer, yeah **you are right** that build has a bug with rear fan. New version is already prepared for release ( based on latest stable 2.0.9.5 Marlin ), please test this: 

[dreamer_2.0.9.5_swap_10022022.zip](https://github.com/moonglow/FlashForge_Marlin/files/9693049/dreamer_2.0.9.5_swap_10022022.zip)

How to control rear case via G-code ( now that guide is valid and retested )

1. If you want to use chamber fan from G-Code you need to disable temperature logic by set cool-down temp to 0 or from Menu->Rear Case->Disable Rear Case Fan
2. Chamber fan index is 2, so you can access it via `M106 P2 S<speed>` ( make sure what you disable cool-down logic before )

**Comment by fbb034** [comment]
it works perfectly now, THANKS!!!

**Comment by digital0785** [comment]
Been trying to get this to work as additional cooling triggered off extruder 2 fan speed request has anyone gotten this figured out in cura? I have rear case fan disabled on the screen and i tried just added a g code command after every layer but it says it's unrecognized even though it works if i just send it from pronterface.
