### ISSUE TITLE
Printer does not start when building firmware from source code

### ISSUE THREAD

**Issue by slimfy1** [moonglow/FlashForge_Marlin#122]
Hello!

When building from source the printer does not start (I tried different options). I build in Visual Studio Code + Platformio. Pre-compiled versions work fine.

**Comment by freeifier** [comment]
I would recommend using the marlin_builder.sh in the repo you can specify different build options. Make sure to also clone the submodules so when cloning also type --recursive so the submodules will geht downloaded too.

 When I tried with platformio it did not work too and also the files were considerably smaller than the prebuilt ones.

**Comment by moonglow** [comment]
@slimfy1 Hi!

You need to encrypt your firmware before flash it to printer. FlashForge bootloader assume that printers firmware is encrypted with my  [flashforge_firmware_tool](https://github.com/moonglow/flashforge_firmware_tool). As example you can check that step in `marlin_builder.sh`. 

p.s: sometime i will found a python programmer ( to port my encryption tool ) and integrate firmware encryption script to Marlin build system.
