### ISSUE TITLE
Compiling FlashForge/Dremel Marlin 2.0.9.5 - Moonglow v0.15.0

### ISSUE THREAD

**Issue by gordonmoore9** [moonglow/FlashForge_Marlin#127]
I compile using Visual Studio Code. When compiling v0.15.0 I receive a terminal message as follows:

Marlin\src\module\planner.cpp: In static member function 'static void Planner::buffer_sync_block(BlockFlagBit)':
Marlin\src\module\planner.cpp:2864:35: warning: 'void* memset(void*, int, size_t)' clearing an object of type 'block_t' {aka 'struct block_t'} with no trivial copy-assignment; use value-initialization instead [-Wclass-memaccess]
 2864 |   memset(block, 0, sizeof(block_t));
          |                                   ^
In file included from Marlin\src\module\planner.cpp:65:
Marlin\src\module\planner.h:190:16: note: 'block_t' {aka 'struct block_t'} declared here
  190 | typedef struct block_t {
         |                        ^~~~~~~

Is this an issue?

**Comment by moonglow** [comment]
Hi @gordonmoore9 !

this is just a compiling `warning` message, not an issue .
