### ISSUE TITLE
2 color printing issues

### ISSUE THREAD

**Issue by digital0785** [moonglow/FlashForge_Marlin#138]
not sure if i'm doing something supremely dumb or what.. but when i try to do 2 color printing a few things happen. 1 it puts the first layer down with the  "correct" extruder, however after that it doesn't change extruders like it should it prints the whole thing with the other nozzle mind you that should only be used for the inner part. 

additionally it keeps stopping right over the part when it "should" be switching nozzles and purges a bunch of filament which I'm assuming is from having the .25 mm nozzle switch prime amount .. but like i said it does actually switch nozzles so it stops at the corner of the model purges a big blob .. then moves to the prime tower does its loop and goes back to printing with the same nozzle 
![image](https://user-images.githubusercontent.com/74274738/213820149-001d5fce-83fc-41ee-8ee8-36bb0daa2cdd.png)
![image](https://user-images.githubusercontent.com/74274738/213820199-5c6489c4-4787-42f8-ad8c-e4b9961a405a.png)
![image](https://user-images.githubusercontent.com/74274738/213820345-840b14b7-b864-44ea-8180-4e4144cced07.png)
![image](https://user-images.githubusercontent.com/74274738/213820393-ec1bb7a2-b4d6-4f40-aea7-5bb5920b5036.png)

![image](https://user-images.githubusercontent.com/74274738/213820512-b4a4b41d-9bba-46f9-9b5c-63397340a919.png)
![image](https://user-images.githubusercontent.com/74274738/213820529-788e64c4-e2f4-4dc3-b977-e924e0e43aef.png)
![image](https://user-images.githubusercontent.com/74274738/213821009-799bf119-bff8-400f-86f9-76f74c816b22.png)
I have each set to the appropriate nozzle to use but it doesn't seem to care.. the gcode preview in cura shows it being the appropriate nozzles (i have the one nozzle printing at 60 vs the other printing at 80 so it's a very obvious difference) but best it does is print the prime line.. the appropriate part of the brim and first layer in the right extruder but it never goes back the only t0 in the gcode is the initial extruder selection then the cool down at the end

sorry for the bother trying to get it dialed in and this was the last thing I needed to calibrate and i've it a road block.

also I forgot to add whenever I pid autotune it tells me it cant save to eeprom and it definitely doesn't as when it was saved it was ROCK solid on the proper temp ... but now it's back to over / under shooting by 3* if not more..

**Comment by digital0785** [comment]
it's definitely something with cura superslicer works fine .. hmm I'll ask that group again

**Comment by Spinboost** [comment]
What did you do to solve the problem of it switching extruders and putting a blob down before going to the prime tower?

**Comment by digital0785** [comment]
Honestly i think it was just from the PID autotune. Now it holds better so instead of over and undershooting it holds steady so it goes to the corner then is like oh we good keep moving. Tbh i re set it up since it wasn't switching extruders at all and i did the PID at the same time. But i think it was the PID
