### ISSUE TITLE
Nozzle Park Position on Dreamer Nx

### ISSUE THREAD

**Issue by tckb** [moonglow/FlashForge_Marlin#14]
The Park position currently is placed in a weird place which isn't really convenient for changing filament.  Normally the park position is out of the printable area meant for purging filaments.

The current park position is 20,140,22
![IMG_8102](https://user-images.githubusercontent.com/939542/113977841-7817f980-9843-11eb-8f69-db1057ad5349.JPG)
  
Park  position should be 270,150 

Park position is defined by  `NOZZLE_PARK_POINT` 

refer: https://marlinfw.org/docs/gcode/G027.html

Also, the save and go to park position is not enabled.  This needs `PARK_HEAD_ON_PAUSE` to be enabled - 

ref: https://marlinfw.org/docs/gcode/M125.html

**Comment by moonglow** [comment]
>Park position should be 270,150

You mean something like right-front position ? center of bed is 0,0 and this position now out of border.  Yep i think it is reasonable.

**Comment by tckb** [comment]
@moonglow I mean right-back position (close to the rear of the printer). with the new changes to the bed origin I am not too sure, the exact position but this is the  x-soft-limit, y-soft-limit . I don't really care of the z, you could raise the z to 2 mm. 

I want the back because there's already a place for filament dump (the space for 'right' spool holder, in nx this is empty)

**Comment by moonglow** [comment]
> the space for 'right' spool holder, in nx this is empty

Ok i will try to find better place for Dreamer and Inventor too

**Comment by tckb** [comment]
@moonglow any plans to release it in v0.8?

**Comment by moonglow** [comment]
if new parking position is OK for you ( latest firmware from #12  ) i will release it in few days, need to make some other improvements.

**Comment by tckb** [comment]
whats the current park position in #12  I'd prefer the x and y soft-limits. I don't mind waiting couple of days ;)  setting my filament routine

**Comment by moonglow** [comment]
> whats the current park position in #12

 `X_MAX - 10, Y_MIN + 10` as universal solution ( RIGHT FRONT ) for all ,but for you i will build special version with  *_la and   `X_MAX - 10, Y_MAX - 10 ` if you want. Right-front looks comfortable for me you can easy access to nozzle to clean and so on

**Comment by tckb** [comment]
thanks @moonglow  I will test both the solutions to see which one works.

**Comment by tckb** [comment]
After testing v0.7_la 

I would like a universal solution rather having a tailored solution, although I'd recommend `X_MAX, Y_MAX - 10`  the 10mm is a bit close to the bed.

**Comment by tckb** [comment]
closing this because i configured it in the fork
