### ISSUE TITLE
Binary firmware flavours

### ISSUE THREAD

**Issue by kostuch** [moonglow/FlashForge_Marlin#148]
Hi, I'm going to flash my FF Dreamer with Marlin firmware and have a question about released binaries.
In zip I found eight versions for my printer and I wonder which one should I use?
_la
_swap
_swap_la
_dir
...etc
Could you explain the differences?

**Comment by moonglow** [comment]
Hi!

Please refer to [WIKI](https://github.com/moonglow/FlashForge_Marlin/wiki/Prebuilt-Marlin-firmware) page.

**Comment by kostuch** [comment]
Thank you for prompt answer.
As I understand, there is no method to check in advance if I need regular or _dir version. Just flash and check if printer works as expected.

**Comment by moonglow** [comment]
Yep you are right.
