### ISSUE TITLE
🐛 [BUG] - <ff_fw_writer will not launch>

### ISSUE THREAD

**Issue by WillowW1sp** [moonglow/FlashForge_Marlin#159]
### Description

it will initially throw an error saying that it cannot find the msvcr120.dll file: 
![image](https://github.com/moonglow/FlashForge_Marlin/assets/5751664/11df6e3f-5edc-4538-9d1c-324045a31e2e)

then after copying the dll to the folder it will instead throw this error message instead: 
![image](https://github.com/moonglow/FlashForge_Marlin/assets/5751664/692f7d92-d83c-4160-9a5f-2e5e73b818fa)

After doing windows updates, running sfc /scannow, and redownloading the file multiple times I still cant seem to get the flasher to launch. 

### Reproduction steps

```bash
1. Download from GitHub
2. extract files 
3. run the application with the dll files copied into the folder
```

### Printer

FlashForge Dreamer

### Marlin Version

N/A

**Comment by qwertychouskie** [comment]
Remove the manually copied DLL, then install https://www.microsoft.com/en-us/download/details.aspx?id=40784 (both the x86 and x64 versions).

**Comment by WillowW1sp** [comment]
Ah that was it, I had the x64 version installed but not the x86
