### ISSUE TITLE
Bought broken FlashForge Dreamer any ideas ?

### ISSUE THREAD

**Issue by sandmix** [moonglow/FlashForge_Marlin#163]
### Summary

Bought this printer with long motherboard power turns on I see some of the leds turs on on MB, not detected when usb pluged boot0 with vcc doesn't put it in DFU. Next thing want to try st-link but need to find it before. 
I see that controller has 3v on vcc so power goes to it, wanted to ask what has 16GB microSD on it because mine is empty. if stlink doesn't help I'm planning to resolder STM chip. 
Does someone has any experience recovering this type of machines ?
Thanks 

### Basic Example

Recovery broken MB

**Comment by Mrnt** [comment]
Micro SD card slot is for internal (print file) memory and can be used to update the firmware. It should not matter if the slot is empty.
Could be firmware is bricked in which case you will prob need stlink to refresh the firmware.

**Comment by sandmix** [comment]
I resoldered the CPU but can't find anywhere backup of original STM dump, if someone can please share it would be really nice. Thank you.

**Comment by sandmix** [comment]
Used [tracedgod](https://github.com/tracedgod) bootloader everything works. Thanks.
