### ISSUE TITLE
Source code released !

### ISSUE THREAD

**Issue by moonglow** [moonglow/FlashForge_Marlin#18]
## Some specific defines:

`FF_FLASHAIR_FIX` - enables temporary fix for Toshiba FlashAIR cards, because they not works in current Marlin configuration ( you need insert such cards twice for now )
`FF_INVENTOR_MACHINE` - build firmware for FlashForge Inventor machine
`FF_DREAMER_MACHINE` - build firmware for FlashForge Dreamer machine
`FF_DREAMER_NX_MACHINE` - build firmware for FlashForge Dreamer NX machine
`FF_EXTRUDER_SWAP` - for two heads machine ( Dreamer and Inventor ) you can swap extruders, because by default left extruder has index 1 and right one has index 0 ( as it was in original firmware ) but if you prefer more logical extruder position you can swap it

## Firmware encryption:

FlashForge bootloader accept only encrypted firmware you must encrypt your binary before flash it to printer, you can use my encryption tool for that: [FlashForge firmware tool](https://github.com/moonglow/flashforge_firmware_tool)

## Marlin upgrade:

My version has some new drivers and hacks to make marlin works with FlashForge you must fully understand what you doing if you want to merge new version of Marlin in future. I do not recommend do it for novice users.

**Comment by tckb** [comment]
@moonglow thanks for releasing the source!  I already have couple of  updates planned,  #15
