### ISSUE TITLE
Marlin 2.0.8.2 builds for FlashForge Dreamer NX/Dreamer/Inventor

### ISSUE THREAD

**Issue by moonglow** [moonglow/FlashForge_Marlin#22]
Marlin introduce new 2.0.8.2 version with lots of improvements and other, read more here: [Marlin 2.0.8.2](https://github.com/MarlinFirmware/Marlin/releases/tag/2.0.8.2)

- [classic_ui_05312021.zip](https://github.com/moonglow/FlashForge_Marlin/files/6568633/classic_ui_05312021.zip) archive for old school guys - binaries with Marlin classic multi-language ui ( Russian/English/Finnish ) ( **2.0.8.2** )
- [color_ui_05312021.zip](https://github.com/moonglow/FlashForge_Marlin/files/6568635/color_ui_05312021.zip) archive - binaries with Marlin modern multi-language ui ( English/Russian ) ( **2.0.8.2** )
- [mks_ui_05312021.zip](https://github.com/moonglow/FlashForge_Marlin/files/6568643/mks_ui_05312021.zip) archive - binaries with multi-language ui from Makerbase ( **2.0.8.2** )

| Classic UI | Color UI | MKS UI |
|----------|----------|----------|
|![classic_ui_mini](https://user-images.githubusercontent.com/1655387/117437507-fb0e9b80-af38-11eb-9fb9-b309543220a1.jpg)|![color_ui_mini](https://user-images.githubusercontent.com/1655387/117437559-08c42100-af39-11eb-8d13-ac0bb497c5ca.jpg)|![mks_ui](https://user-images.githubusercontent.com/1655387/120157267-83602380-c1fb-11eb-9f93-14aecdee5a28.jpg)|

Update log:
- 31-05-2021 synced with 2.0.8.2, add MKS UI
- 21-05-2021 synced with upstream repo
- 17-05-2021 synced with 2.0.8.1 with English and **Russian** language support for Marlin UI
- 07-05-2021 synced with [latest Marlin repo commits](https://github.com/MarlinFirmware/Marlin/commit/76ec7040f1209ea9e0f0132782be62f3054601bb)

**Comment by moonglow** [comment]
So... after few hours of printing i can say what it works well stable for me ! I think now i can recommends this build for testing to everyone

**Comment by Lucien-X** [comment]
@moonglow 
Seems great!
But now I am stuck with the v0.9.1 firmware published yesterday.
https://github.com/moonglow/FlashForge_Marlin/issues/24
Any help?

----------------------------------------------------
Never mind , the problem is solved with a virtual machine.  😄

**Comment by moonglow** [comment]
synced with upstream repo

**Comment by moonglow** [comment]
update to 2.0.8.2, add MKS UI support
MKS UI in action: 
- https://youtu.be/KVw4Sij5VpY
- https://youtu.be/NVadaPB5D4Q
