### ISSUE TITLE
More precision step/mm, feedrate and accel settings

### ISSUE THREAD

**Issue by moonglow** [moonglow/FlashForge_Marlin#36]
default settings:
```
step_per_mm ( black pulley )
X: 88.909720
Y: 88.909720
Z: 400.000000
E1: 96.275202
E2: 96.275202

max_feedrate ( mm/s )
X: 300
Y: 300
Z: 19.5
E1: 26.6666666667
E2: 26.6666666667

accel:
X: 1000
Y: 1000
Z: 150
E1: 4000
E2: 4000
```

**Comment by OneMonkeyArmy** [comment]
Just curious, how you endup with 6 decimals numbers for the steps/mm ?

and even if it is right, in the advance settings menu, the numbers are only displayed with 1 decimal !!!

**Comment by moonglow** [comment]
>Just curious, how you endup with 6 decimals numbers for the steps/mm ?

You are absolutely right! This is just values from original firmware ( and yep they use such precision constants ), we can set such values from GCode, but not from LCD menu.
