### ISSUE TITLE
Enable advanced pause feature

### ISSUE THREAD

**Issue by tckb** [moonglow/FlashForge_Marlin#4]
It seems "ADVANCED_PAUSE_FEATURE" is not enabled in the firmware.  https://marlinfw.org/docs/configuration/configuration.html#advanced-pause

as mentioned in #3  unload and load filament isn't accepted

**Comment by moonglow** [comment]
added in v0.3

**Comment by tckb** [comment]
Thanks! although the filament  loading and unloading procedure is a bit weird. I am not too familiar with Marlin interface but there is no cancelling filament loading or unloading process.  I will do a bit more testing, will possible create another issue. I am closing this now!
