### ISSUE TITLE
Reverse Polarity of E2 Extruder?

### ISSUE THREAD

**Issue by DDMH** [moonglow/FlashForge_Marlin#46]
I have flashed "fw_2.0.9.1_dreamer_swap_06302021.bin" to my Dreamer. When I use "Change Filament"->"Load E2" (right extruder), the right extruder seems to pull the filament out instead of pushing it in. The Dreamer dual extruder assembly is similar to this one in the image below:

![HT-Dual](https://user-images.githubusercontent.com/86676495/127780131-285cf116-c939-47a7-86c7-84aedbf7ab32.png)

Since the two extruder motors rotate in opposite directions when printing, I think the polarity of E2 needs to be flipped in the firmware.

**Comment by moonglow** [comment]
Hm... very strange thing looks like they must goes in to the same direction and i never saw such things before.Thank you i will build special version for you and if all be OK we need to think how it can be resolved while autobuild.

**Comment by DDMH** [comment]
Today I tested it again and the motor of E2 was in reverse. When I used "Unload E2", the filament was actually being loaded. Same thing happened when I sent Gcode directly through Pronterface.

![Dreamer Extruders](https://cdn.shopify.com/s/files/1/0180/7671/products/Dreamer_dual_head_2000x.png)

**Comment by moonglow** [comment]
If your stock extruder do same and original FF firmware works OK with that, you can try this version:

[e1_dir_inverse.zip](https://github.com/moonglow/FlashForge_Marlin/files/6941304/e1_dir_inverse.zip)

p.s: if all be OK you can build your own version, just set `INVERT_E1_DIR` to `true` in `Configuration.h` file.

**Comment by DDMH** [comment]
Thank you, moonglow! I will test it later today and report back.

The first photo (Flexion extruder) was only used to show the dual extruder assembly, because it's similar to the stock one. I still have the stock extruders on my Dreamer. Sorry for the confusion.

**Comment by DDMH** [comment]
@moonglow I tested using the "Load E2" option and extruding manually by sending Gcode via Pronterface. Both methods worked flawlessly. Thanks again for the quick patch.
