### ISSUE TITLE
M907 Overcurrent Error

### ISSUE THREAD

**Issue by OrangeBannana** [moonglow/FlashForge_Marlin#75]
Hi, im pretty new to the firmware side of 3d printing, I loaded firmware onto my PowerSpec Ultra and im getting an m907 overcurrent error, im slicing in the ultra3d slicer with Slic3r. Maybe im  making a newbie mistake but I cant figure this out.

any and all ideas would be appreciated, I can provide more details if needed

**Comment by moonglow** [comment]
Hi @OrangeBannana !

You need to read that article and change your G-code start sequence: [LINK](https://github.com/moonglow/FlashForge_Marlin/wiki/%5BATTENTION%5D-Avoid-using-FlashForge-original-firmware-G-Codes)

over-current protection just helps you to eliminate what your motor current settings is wrong and dangerous you can omit it or change according to article.

**Comment by OrangeBannana** [comment]
Thanks, I understand most of this, but how do I know how many amps to set my motors to?

**Comment by moonglow** [comment]
@OrangeBannana you can use defaults settings because our printers is same `M907 X0.7 Y0.7 Z0.35 E0.7`and adjust if needed ( Z motor has a current limits only up to 0.45A do not try to make it bigger, XEY can be 0.7-0.9 i think it was safety too )

**Comment by OrangeBannana** [comment]
Thank you, there are several gcode commands that dont have a marlin equivalent (idk if thats the right word)  at all it seems, or some that i think might but im not sure, if theres no marlin equivalent should I just remove them? specifically the following commands

M132 recalls home offsets
M135 load right extruder offset
M133&M134 stabalize temperatures 
G130 changes stepper vrefs

Thanks for the help

**Comment by moonglow** [comment]
You can adjust your startup code from here ( i use it with my one head machine ): [G-Code examles](https://github.com/moonglow/FlashForge_Marlin/wiki/FlashForge-Dreamer-NX-Start-End-G-Codes-examples) or grab it from other  head machines who uses Marlin firmware

**Comment by OrangeBannana** [comment]
Thanks for all the help, I think I can work things out. Also is there a way to reinstall the original firmware

**Comment by moonglow** [comment]
@OrangeBannana 
You can tries two methods ( because PowerSpec Ultra is **FF Dreamer** clone ):
1. Try to use my firmware updater, what will tries update firmware from BOOTLOADER mode: [LINK](https://github.com/moonglow/FlashForge_Marlin/wiki/Windows-instalation-guide)
2. Try to use that [GUIDE](https://github.com/moonglow/FlashForge_Marlin/wiki/Installing-Marlin-on-Dremel-3D20), but rename firmware to `dreamer.bin` not `dremel.bin`

**Comment by OrangeBannana** [comment]
Thanks, also I havnt seen a ready made copy of start/end g code for this printer, is there somewhere I can post it when im done so other people can use it, along with a Cura profile
