### ISSUE TITLE
Swapped firmware for Dreamer moves extruder to the wrong side when swapping extruders

### ISSUE THREAD

**Issue by Lycowolf** [moonglow/FlashForge_Marlin#76]
Hi,

I tried to use dreamer_2.0.9.1_dir_swap_la_08152021 firmware with my dual-extruder Dreamer, and homing moved the left nozzle to the center of the bed area (as expected). Sending T1 command then moved the extruder assembly to the *right*, off-centering it (as if there was one nozzle left from the left one).

Flashing the non-swapped version gave me the correct behaviour: homing centered the right nozzle, switching to T1 moved the assembly to the right, centering the left nozzle.

**Comment by moonglow** [comment]
Hi !

You can try to set right hotend offset via Marlin itself ( G-Code or Menu ) and tell me what will works for you. I will try to check that behavior too. Thanks

**Comment by Lycowolf** [comment]
Well, do I feel dumb :-) of course it helped. I set hotend offset X=34 (positive) and now it moves the extruder the right way. Thanks.

**Comment by Lycowolf** [comment]
(Just to be clear: I am leaving this issue open because you mentioned you want to check the behaviour too. I consider the problem solved for me.)

**Comment by moonglow** [comment]
Yep, thank you! i will check it myself and make that behavior by default

**Comment by ammoniak** [comment]
I had the same issue and setting it to 34.0 instead of -34.0 works fine.
