### ISSUE TITLE
Failed to set trigger

### ISSUE THREAD

**Issue by loibucket** [moonglow/FlashForge_Marlin#83]
Failed to flash, error message below

```
Start Control
Control Success
ok
Control Success
ok
Write file done
Writing to file 0:/sys/dreamer.bin Length 564464
ok
Failed to set trigger
Stop
```

Flashforge Dreamer, single motherboard version, latest color ui firmware, latest ff_flasher

**Comment by moonglow** [comment]
Hi @loibucket !

Thank you for report ! I think i need to find windows machine to reproduce that problem.

**Comment by HDHristov** [comment]
Same issue here. It should be noted, that it tries to write way past the bootloader. It is actually connecting to a fully booted Dreamer.
Looks like it is a bootloader connection issue. My dreamer was on the latest 2.15 firmware, maybe they changed something in the bootloader? Just wild guessing here.
Also tried to downgrade to 2.14 - same outcome, but if it was a bootloader change it might be still there...

**Comment by HDHristov** [comment]
@moonglow would it be possible to use FlashPrint to write the Marlin binary?

On a side note, is there a description of the different prebuilt binaries? I'm referring to the different dir_la_swap options.
Thanks!

**Comment by moonglow** [comment]
@HDHristov bootloader is unchangeable part of printer firmware, it will written only once by manufacture. You can try to update firmware from bootloader mode via FlashPrint too, but i think we need to fix my updater

**Comment by moonglow** [comment]
@loibucket and @HDHristov 

Can you tried updated FF Flasher ? It will also allows now to set trigger only ( it will provoke bootloader to update firmware from 'sys' folder of internal uSD card ) [LINK](https://github.com/moonglow/FlashForge_Marlin/wiki/Windows-instalation-guide)

*version from 06_01_2022
p.s: make sure what your windows system installs windows FF bootloader driver and it not looks like unknown device in device manager, because you can see that driver install for application firmware and no drivers installed for bootloader.

**Comment by HDHristov** [comment]
Will check tomorrow (although I already flashed using Linux). Thanks!

**Comment by HDHristov** [comment]
Still does not work. Now it only says "Wait for printer" until it times out.
I can shortly see "FlashForge 3D Printer" device appearing in the Device manager when I switch on the printer. Not sure this is the bootloader device driver we need.

**Comment by moonglow** [comment]
If software can't catch the bootloader that mean what you do not install driver to bootloader device. If you will install it all be OK i think

**Comment by HDHristov** [comment]
It looks like I'm missing something. Where do I get that driver from?

**Comment by moonglow** [comment]
>It looks like I'm missing something. Where do I get that driver from?

![1](https://user-images.githubusercontent.com/1655387/148449695-8d30af2e-d61a-40c4-906d-69ec53620d29.png) - it will appear before application was run
Yep... if my tool can't find a printer it means that not driver installed. You can find drivers here ( in my case ): `x:\Program Files\FlashForge\FlashPrint 5\driver\win7`
And you must be quick to catch device and try to install drivers. `Libusb` can't access USB device without driver was installed on Windows.

**Comment by gordonmoore9** [comment]
@moonglow - I have had trouble uploading the latest Marlin firmware using your updated FF Flasher.

However success did eventually occurred doing the following steps.

First for the purpose of explaining here, I flashed back to the FlashForge Dreamer firmware for a defined starting point.

My PC runs Windows 11. I opened Device Manager which lists device 3D Printer - FlashForge Dreamer 3D Printer as per picture.

![1 FlashForge Firmware Currently Installed](https://user-images.githubusercontent.com/25269386/149831960-87cef663-23a0-4bb4-a336-c4e332e31c56.jpg)

Next opened FF Firmware Writer and selected "dreamer_2.0.9.3_la_01102022.bin". Powered off the Dreamer.

Clicked START in FF Firmware Writer and **quickly** powered on the Dreamer (for other readers note **quick power-on is crucial**). Marlin firmware started to load as per this picture.

![2 Marlin Firmware Installing](https://user-images.githubusercontent.com/25269386/149832444-69e49045-787a-47ca-860e-ffff564e10f8.jpg)

Upon completion the Marlin Color UI appears on the Dreamer LCD.

I noticed in Device Manager that the device 3D Printer - FlashForge Dreamer 3D Printer was gone but there is now Ports (COM & LPT - USB Serial Device (COM3) as per this picture.

![3 Marlin Installed - Connection Now COM3](https://user-images.githubusercontent.com/25269386/149833151-4cae7dd3-e8a9-48d6-80c1-1d815c36472b.jpg)

OctoPrint happily connects the Dreamer now via COM3 and no problem controlling the Marlin firmware.

In Device Manager the device when connecting as FlashForge Dreamer 3D Printer has hardware ID USB\VID_2B71&PID_0001.

Under the Marlin firmware, device USB Serial Device (COM3) has hardware ID USB\VID_0483&PID_5740.

Is it correct that the device changes to USB Serial Device (COM3) for hardware ID USB\VID_0483&PID_5740?

**Comment by moonglow** [comment]
>Is it correct that the device changes to USB Serial Device (COM3) for hardware ID USB\VID_0483&PID_5740?

Yep, because Marlin provides their own code to implements USB serial class client and that's VID/PID is using from Marlin driver by default. 

p.s: thanx for tips, i hope it will helps to other users
