### ISSUE TITLE
MKS UI not working on Dreamer

### ISSUE THREAD

**Issue by scotty-sw** [moonglow/FlashForge_Marlin#86]
Hi, before my problem I would like to say your work is amazing and much appreciated.

So I am trying to install MKS UI on my Dreamer but am unable to get it to work, I have Colour UI working using flash writer with no problems if that makes a difference. After the MKS install the screen bootloops the start bmp.

I have connected W25Q128 with dupont wires to the wifi socket but am not 100% if it is done correctly as the chip overheats after the firmware install. I followed the pinouts as per the link and connected the first SPI flash module based on numbers on the back of the WIFI module I disconnected, so if looking at the coreboard (REVH) with the writing in the correct orientation pin 1 was top left with 2 bottom left, then 3 next to 1 etc. My Dreamer only has 10 pins for the wifi so I went with that configuration. When connected like this the SPI Flash light doesn't come on during the process if that makes a difference.

Also when putting the assets onto the SD card I have been doing this on the internal SD card, do I put it in the main SD card directory or in the SRC folder with the firmware and start bmp.

When adding the asset do I put the assets folder into the directory or just the files contained in the assets folder.

Thanks in advance, any help is appreciated.

**Comment by moonglow** [comment]
Hi @scotty-sw !

Assets must be located at root of your main ( BIG ) SDCard.

>When connected like this the SPI Flash light doesn't come on

I think that's mean what your pin connection is not correct, can you provide me photo of module connection ? i will try to check it

**Comment by scotty-sw** [comment]
![1](https://user-images.githubusercontent.com/96465599/146910619-acaee673-a8d5-429c-a283-8eca1dbc0224.jpg)
![2](https://user-images.githubusercontent.com/96465599/146910626-248f38ee-5687-4825-9413-8477342729b8.jpg)
![3](https://user-images.githubusercontent.com/96465599/146910644-14b91ed9-5331-4f4b-83c1-96bff657f45b.jpg)

Hi moonglow, thanks for the help images as requested, also do I put the assets folder on the big SD card or just the files inside the folder

**Comment by moonglow** [comment]
Oh.... looks like you do mistake in socket row... if your SPI flash is not damaged all must be OK, just recheck all pins with this ( red dot is pin 1 ) i also rotate original schematics from WIKI to make it looks from that pov. Because for now your GND pin is connected to FLASH VCC and VCC pin to FLASH GND ( thats why your module overheated ) and all other pins wrong too.


![connection](https://user-images.githubusercontent.com/1655387/146915185-26e80eb5-d00f-4f18-a25d-f5b9324288c6.jpg)

**Comment by scotty-sw** [comment]
Hi Moonglow thanks again, the light on the SPI flash is now working, now the screen boots up with some square boxes that say no data, looks like it isn't doing the file transfer?

**Comment by moonglow** [comment]
You need to install `assets` that was comes with firmware, just put `assets` folder to root of your external FullSize SDCARD ( it will plug from printer side and must be preformatted to FAT32 ) and turn-on your printer.... firmware will founds that dir and will install needed data from it (  if your SPI flash is OK  ) you will see messages on black screen then it was finished you will see MKS UI

**Comment by scotty-sw** [comment]
Thanks heaps moonglow, it's now working, does the buy you a coffee accept paypal, will definitely do it if it does, Thanks again

**Comment by moonglow** [comment]
!) Nice... btw BuyMeACoffee service is not working anymore because they drops PayPal support ^_^ i will change to something else soon ... Tnax

**Comment by scotty-sw** [comment]
Okay will check back to see if you find something else, Cheers
