### ISSUE TITLE
Purposes of all the provided files

### ISSUE THREAD

**Issue by gio3k** [moonglow/FlashForge_Marlin#89]
When extracting the ZIP full of prebuilt firmware there are many different options for 1 machine

For me the one without any option works but I need to use swap for my extruder, so should I use dir_swap, swap, or swap_la?

**Comment by gordonmoore9** [comment]
Look in Discussions for :-

Differences among bin files #43

**Comment by giodotblue** [comment]
oh amazing, thanks!
