### ISSUE TITLE
PowerSpec Ultra 3D - Reboot cycle after firmware update

### ISSUE THREAD

**Issue by bgreat** [moonglow/FlashForge_Marlin#90]
I decided to update my working PowerSpec Ultra 3D from the current Dreamer v2.15.20200917 to FlashForge_Marlin dreamer_2.0.9.3_01102022.

FF Firmware Writer did not want to work for updating the original firmware. I was able to perform the firmware update via the FlashPrint 5 Tools, Update Firmware menu. The firmware send was successful and showed success in writing the image on reboot of the printer. After the update, the initial boot screen was displayed, followed by a Marlin splash screen (all excited). Then after about 10 seconds, the controller rebooted, returned to the boot splash, then to the Marlin splash screen, and the cycle repeats... Power on/off or reset has no impact.

To recover, the FlashPrint firmware update would not work, but I was able to use FF FIrmware Write to restore the prior firmware from backup.

I did find two methods that worked to restore the prior firmware:
  1. Copy the old firmware to sys/dreamer.bin on printer internal SD, then use FF Firmware Writer to trigger the firmware update.
  2. Use FF Firmware Writer to download and trigger the firmware update to the prior version over USB. Interesting that FFFW works to restore the old version when stuck with a bad load of the new firmware.
 
So, I'm back to running the Dreamer firmware on my PowerSpec Ultra 3D. 

My PowerSpec Ultra 3D configuration:
- Model No: PS3D-ULTRA
- Purchase: Mar-2016
- FlashForge CoreBoard Rev J, V 2.2
- FlashForge DriverBoard Rev E, V 2.3
- Firmware: Dreamer 2.15 20200917

I typically work with ABS, PETG, nylon, and TPU on a glass bed w/ Kapton tape (no bonding agents).

Any guidance for how I may assist in getting this to work on my is welcome.

Enjoy!
Bill

**Comment by bgreat** [comment]
I tried the prior pre-built Marlin versions and experience the same issue.

Doing some more testing, I found I can download my original firmware and revert using FlashPrint if I get the timing correct - bootloader must be active - after boot splash, but before Marlin splash dislays.

FF Firmware Writer also works for the initial firmware load and reverting the firmware if I can time for the bootloader window.

**Comment by bgreat** [comment]
For reference
![C2A1A2B4-0D08-41BD-B198-CA89EA5A48A7](https://user-images.githubusercontent.com/850330/153724961-52da2518-31d9-4638-9edf-7be830598b0d.jpeg)
![1C60FF27-AFB1-4A19-AEBB-5CB63ADDF4F1](https://user-images.githubusercontent.com/850330/153724965-11d40531-e85b-4196-876a-ac791c42bbd9.jpeg)
![55B313E5-AA44-440C-8C42-5517C78EE453](https://user-images.githubusercontent.com/850330/153724967-60e02643-a3e3-429f-86e4-c93172172efa.jpeg)
![B8442A64-A1C0-4D29-AAD6-D213B7A5A63E](https://user-images.githubusercontent.com/850330/153724968-34af25d2-dbb5-4bc7-84b4-682bed89c500.jpeg)

**Comment by moonglow** [comment]
Hi @bgreat !

Wow ! Thanx for so detailed report.... 

> After the update, the initial boot screen was displayed, followed by a Marlin splash screen (all excited). Then after about 10 seconds, the controller rebooted, returned to the boot splash, then to the Marlin splash screen, and the cycle repeats... 

Can you attach USB to PC ( it must appear as virtual serial port ) and attach terminal like [TerraTerm](https://osdn.net/projects/ttssh2/releases/) it can reconnect device after it was disconnected and connected again. Maybe Marlin will out some useful information. Reboots appear for many cases, but usually it means what internal watchdog was triggered and reboot the board. Can you also tries another firmware as example build for one head NX ? Another thing can you remove or insert external ( BIG ) SDCard before run the firmware.

**Comment by bgreat** [comment]
Thanks for the reply! My thought was the watchdog was triggering and causing the reboot. I had not had time to set up the correct dev tools and review the Marlin code base to see if I could track down the issue. 

I'll attach as USB serial and see if any info is returned. I was considering trying to monitor, but got caught up in my "real" day job work before I could attempt to connect. I currently run the current Flash Forge Dreamer firmware, but I will also try the NX build to see what occurs. I normally have an external SD inserted. I believe I tried both with and without, but will confirm.

I am currently out of town for work and will not return until late next week, but will definitely update you on what I am able to find as soon as I have access to the printer. I'll also look into setting up my dev environment for Marlin to see if I can assist in isolating the source of issue.

Great work on getting Marlin working with these 3d printers and I look forward to being able assist in making this functional with my hardware.

Enjoy!
Bill

**Comment by moonglow** [comment]
@OrangeBannana uses firmware on his PowerSpec Ultra #75 .Maybe he can test latest build too...  

>I am currently out of town for work and will not return until late next week, 

Thanks ! will waits for your return

I hope we can locate the problem and fix it. PowerSpaces uses Dreamer motherboards and thats why it strange for me what it not loaded correctly.... BTW if you can [dump your full MCU memory ](https://github.com/moonglow/FlashForge_Marlin/wiki/Backup-printer-firmware) i can recreate such situation on one of my motherboard and fix all it locally.

**Comment by bgreat** [comment]
I have a build environment now configured and was able to run the marlin_builder.sh script and generate a binary.  I cannot test while I am out of town, but will familiarize myself further with the sources.

I did see 2 warnings output while building, but am not too concerned based on the content:
![image](https://user-images.githubusercontent.com/850330/154778252-f5302053-0726-4dd5-bfb9-616f003ffd01.png)
![image](https://user-images.githubusercontent.com/850330/154778288-b9fc4f9a-188c-474b-a03c-9998ed8fb3ce.png)

I am still looking to return to testing at the end of next week and will send an update.

Enjoy!
Bill

**Comment by moonglow** [comment]
>I did see 2 warnings output while building, but am not too concerned based on the content:

Thats OK... just means what Marlin firmware configuration headers are embeds to firmware and can be extracted via [M503](https://marlinfw.org/docs/gcode/M503.html) new feature for 2.0.9.3  . Another WARNING is ON top because thermal chamber protection it is not good idea for our printer construction, so i disable it.

BTW if you want to debug firmware via JTAG programmer ( i really recommends you first to make a full dump of MCU memory and i can also helps to you with my hardware setup )  you need to build DEBUG build via VS Code + PlatformIO and run resulting ELF firmware

**Comment by bgreat** [comment]
It was the watchdog timing out.

It did not like something about my SD card. I removed it, reformatted, and now everything is working as expected.

I still need to do my first print, but I did confirm fans, heating, and extrusion are working, plus performed a bed level.

Thank you!
Bill

**Comment by moonglow** [comment]
>now everything is working as expected.

Yeh! nice to read that !
