### ISSUE TITLE
Updating the arduino framework for stm32 to new version

### ISSUE THREAD

**Issue by OneMonkeyArmy** [moonglow/FlashForge_Marlin#91]
If the user update the ardiuno framework for stm32, located in USER_NAME/.platformio/packages/

1-the previous version get renamed with the version added to it's name

2-the new version is named with the correct name, but does not contain, right away the needed files included in the folder named FF_F407ZG, generated by the python script located at 
 buildroot/share/PlatformIO/scripts/generic_create_variant.py

3-Even when restarting the application VS-CODE, forcing the system to updates his path by itself, and clearing the previous build, when starting a new build, the script always recreate the needed files in the old
ardiuno framework folder, and the system uses the ones in the new folder.

4-Sorry, didn't took the time to investigate the Python script, I have solved the problem manually.

5-Maybe I did something wrong, if not, others will have the similar problem soon !

**Comment by moonglow** [comment]
Hm i have no problem with framework update and so on ? anyone has such problem ever ?
