### ISSUE TITLE
Error in Wiki Linux Installation Guide?

### ISSUE THREAD

**Issue by Mrnt** [moonglow/FlashForge_Marlin#92]
I think that this page, [Linux Installation Guide](https://github.com/moonglow/FlashForge_Marlin/wiki/Linux-instalation-guide),  (there is also a typo in the title) may have an error in the instructions:
```
sudo apt-get install python3
sudo apt-get install python-pip
sudo apt-get install libusb-dev
sudo pip install pyusb
```
On Raspbian (which seems to already have python 2.x) the above installs pip2 and `sudo pip install pyusb` invokes pip2

The following however seems to work correctly on Raspbian:
```
sudo apt-get install python3
sudo apt-get install python3-pip
sudo apt-get install libusb-dev
sudo pip3 install pyusb
```

**Comment by moonglow** [comment]
Thank you for tips !
