### ISSUE TITLE
Adding the Flashforge Finder

### ISSUE THREAD

**Issue by MegaProLaser** [moonglow/FlashForge_Marlin#96]

**Comment by moonglow** [comment]
Hi @MegaProLaser !

We already discussed about it here ( [LINK](https://github.com/moonglow/FlashForge_Marlin/discussions/80) ). I can add such printer, but i need actual motherboard from it or someone who can build full pin map from his motherboard and able to make some tests for new firmware. 

p.s: you can also tries hardcore way :) just try to flash dreamer_nx firmware to it if it pin compatible all be OK, but it is dangerous and wrong pin configuration ! **can damage your printer in theory**  !
